### ISSUE TITLE
Google is crawling and indexing the insides of latex2html.org

### ISSUE THREAD

**Issue by pauloney** [latex2html/latex2html#10]
As you can see on this image Google is crawling and indexing the insides of latex2html.org, which is probably not intended since there is no access to the insides of the web-site.

![screenshot from 2017-01-22 16-34-18](https://cloud.githubusercontent.com/assets/2358114/22187763/fd969826-e0c0-11e6-9ba3-5ebf348604bf.png)

**Comment by danielgildea** [comment]
This is just left over from an older version of the site.
