### ISSUE TITLE
Adjust the package to CTAN standards - double file names

### ISSUE THREAD

**Issue by pauloney** [latex2html/latex2html#14]
DoubleFileNames:

```
./styles/chemsym.perl
./XyMTeX-HTML/chemsym.perl

./texinputs/hthtml.sty
./docs/hthtml/hthtml.sty

./texinputs/justify.sty
./docs/justify.sty

./example/Makefile
./cweb2html/Makefile
./docs/hthtml/Makefile
./docs/Makefile

./manual.pdf
./docs/manual.pdf

./cweb2html/README
./IndicTeX-HTML/README

./readme.hthtml
./docs/hthtml/readme.hthtml

./icons/up.gif
./docs/psfiles/up.gif

./texinputs/url.sty
./docs/url.sty
```

**Comment by ozross** [comment]
LaTeX2HTML dates from before TeXLive was commonly available.
Back then it had to distribute some packages to ensure that they were available. That is no longer the case these days. You can kill all the  .sty  files that are available already in TeXLive.
Note that  html.sty  was specifically for LaTeX2HTML, so you probably need to keep this.
Check that the documentation still compiles with newer versions of packages.

For  README  just append a postfix;  e.g.   README.IndicTeX-HTML    README.cweb2html
Not sure why     chemsym.perl   is in 2 places.  That was a separate contribution — not my work.
