### ISSUE TITLE
Adjust the package to CTAN standards - identical files 

### ISSUE THREAD

**Issue by pauloney** [latex2html/latex2html#15]
These files are identical - even without the same name:

```
-rw-rw-r-- 1 ina server 15025 Dec 15 22:09 ./docs/url.sty
-rw-rw-r-- 1 ina server 15025 Dec 15 22:09 ./texinputs/url.sty

-rw-rw-r-- 1 ina server 20274 Dec 15 22:09 ./versions/html2_1.pl
-rw-rw-r-- 1 ina server 20274 Dec 15 22:09 ./versions/i18n.pl

-rw-rw-r-- 1 ina server 257 Dec 15 22:09 ./icons/ch_delet.gif
-rw-rw-r-- 1 ina server 257 Dec 15 22:09 ./icons/ch_del_r.gif

-rw-rw-r-- 1 ina server 288 Dec 15 22:09 ./icons/ch_delet.png
-rw-rw-r-- 1 ina server 288 Dec 15 22:09 ./icons/ch_del_r.png

-rw-rw-r-- 1 ina server 359 Dec 15 22:09 ./styles/harvard.perl
-rw-rw-r-- 1 ina server 359 Dec 15 22:09 ./styles/havard.perl

-rw-rw-r-- 1 ina server 359 Dec 15 22:09 ./styles/havard.perl
-rw-rw-r-- 1 ina server 359 Dec 15 22:09 ./styles/nharvard.perl

-rw-rw-r-- 1 ina server 4455 Dec 15 22:09 ./styles/chemsym.perl
-rw-rw-r-- 1 ina server 4455 Dec 15 22:09 ./XyMTeX-HTML/chemsym.perl

-rw-rw-r-- 1 ina server 60671 Dec 15 22:09 ./versions/html4_01.pl
-rw-rw-r-- 1 ina server 60671 Dec 15 22:09 ./versions/html4_1.pl

-rw-rw-r-- 1 ina server 7704 Dec 15 22:09 ./versions/html2_2.pl
-rw-rw-r-- 1 ina server 7704 Dec 15 22:09 ./versions/table.pl

-rw-rw-r-- 1 ina server 949 Dec 15 22:09 ./styles/amsfonts.perl
-rw-rw-r-- 1 ina server 949 Dec 15 22:09 ./styles/amssymb.perl

-rw-rw-r-- 1 ina server 963145 Jan 21 13:32 ./docs/manual.pdf
-rw-rw-r-- 1 ina server 963145 Jan 21 13:32 ./manual.pdf

```

**Comment by ozross** [comment]
I don't see a problem having identical files that do not change.
e.g.
  /styles/harvard.perl       supports  \usepackage{harvard}
 /styles/nharvard.perl      supports  \usepackage{nharvard}
The support is the same, since the LaTeX user-commands are identical.

On my original development version, one would have been a symlink to the other.
But that doesn't work with  CVS  repositories, so you get 2 identical files.
If you want to add comments that make them different, go ahead.

**Comment by ozross** [comment]
My recollection is that:    versions/table.pl    
is the original file, supporting HTML tables, back in the time of  HTML 2.2.
As the option mechanism was extended to support more versions of HTML,
it became convenient to call it  html2_2 .  
So we just took a copy naming it as:    versions/html2_2.pl    

The package loading mechanism allows  2.2  to be specified, or the original  table .
Again, change them by adding comments, if you really don't want identical files.
Or make one load the other.
