### ISSUE TITLE
tag releases

### ISSUE THREAD

**Issue by johnyf** [latex2html/latex2html#2]
Currently, no releases are tagged in the repository. Based on CTAN, a release appears to have occurred on 2016-6-16 ([latex2html-2016.tar.gz](http://mirrors.ctan.org/support/latex2html/latex2html-2016.tar.gz)). This date is within the range of commits in this repository. Could you please tag past and future releases, so that they can be easily found in history?

**Comment by pauloney** [comment]
The problem with the version number:

-   The sources were last updated in Jan 2017.
-   The program reports: This is LaTeX2HTML Version 2008 (1.71)
-   The Manual has: This document accompanies LaTeX2HTML version 99.1 (beta)
-   On top of it all the manual uses \today to set its date!

The release numbers were standard during the times of Nikos (92-96) and then when Ross picked up he started to use two-number year digits (96 Release 1, 98 Rel. 2 ...) later when the year reached 2000 the whole thing changed to this "Version 2008 (1.71)" that we have right now, but the Manual is still reporting "version 99.1 (beta)". 

Ina wants an increasing number, which may not be possible under a reasonable schema. I prefer something like very clear like:

    Version 1.72 (Released 21 Jan 2017) 

and for all the manuals to be updated automatically.

I checked how the version was set in the code, but was not able to understand all that was set in there. I though there were too many unnecessary twists and turns - but I could be wrong. It would be better for someone with an IDE to check how that is being set, and where else is being used.

**Comment by danielgildea** [comment]
What I get right now is:

    % latex2html --version
    This is LaTeX2HTML Version 2017 (1.71)

the 2017 comes from config/config.pl, and the 1.71 comes from latex2html.pin.
I have been updating the 2017 but not the 1.71.  I am happy to adopt to adopt 
whatever scheme you prefer.

**Comment by pauloney** [comment]
What about changing it to:

     Version 1.72 (Released 21 Jan 2017) 

because that is clear to everyone, and then I'll make sure the manual pick it up automatically... and also getting the hang of increasing the release number. The release/version/date of latex2html has been a thorn for more than 20 years, and then we settle for something that anyone will understand immediately... without having to check anything.

**Comment by johnyf** [comment]
Thank you for analyzing the current state of versioning. As a reference on the topic of versioning, I would recommend [PEP 440](https://www.python.org/dev/peps/pep-0440/). The Python community has been using mostly version numbers in the form `X.Y.Z`.

With this versioning scheme, one can choose to follow [semantic versioning](http://semver.org/). I do not strictly follow semantic versioning (though my own packages are still below `1.0.0`, it so coincidentally I do, because semantic versioning places fewer constraints on versions in that range). Nevertheless, I do support the concerns it raises, and I mostly follow a "shifted" variant, where API changes result in increments of `Y`, instead of `X`.

I think that it is informative to present the version to the user accompanied by a date. But I don't think that the date should be part of the version scheme. Of course, there are some projects that implicitly incorporate the date, by letting `X` be the year (and possibly the other numbers the month and day).

**Comment by ozross** [comment]
I'm surprised that the manual says  99.1 (beta).
Does that discuss use of frames ?

I was working on LaTeX2HTML through to 2004; I'm sure that I used 2K1  for  2001 and maybe there was a 2K2 sometime as well. Maybe that was just for filenames?
But the servers and hard-drives with my working versions are long dead now.
Though my uni probably still has a back-up; but having this would only complicate things further.

**Comment by pauloney** [comment]
I would love to have it!

Paulo Ney

**Comment by pauloney** [comment]
Reading on PEP 440 and learning a lot! Thanks for the tip @johnyf.

**Comment by pauloney** [comment]
@ozross There are some talk of frames in this 99 beta version of the manual, and there is a package included in the distribution. If you are able to dig a backup of your server from that time - I would love it ...

**Comment by pauloney** [comment]
I certainly do not have any problems with the year being a part of the versioning of the package, but I would like to avoid this:

     LaTeX2HTML translator Version 2K.1beta (1.47)
     LaTeX2HTML translator Version 2K.1beta (1.48)
     LaTeX2HTML translator Version 2K.1beta (1.49).
     LaTeX2HTML 98.1 release (February 19th, 1998)

that shows two classes of problems with the current versioning.

**Comment by johnyf** [comment]
Just as a philosophical comment on years being part of a version in a capacity different than numbers within a version identifier that aren't semantically distinguished, only informally (i.e., one may think of a *year* when they read the number `2017` in the version identifier `2017.10.2`, but it has no temporal meaning within a PEP 440-style definition): numbers are neutral and timeless. Years assume a specific calendar system. Numbers are the same for any civilization, calendar systems aren't.

**Comment by pauloney** [comment]
Agreed 100%! I learned a lot by reading PEP 440, and the date should have no place there unless we are doing something like:

    LaTeX2HTML translator Version 1.49 (Released 02 February 2017)

would be the best. We do not have an API, so there is not much of a need to X.Y.Z, but would be very nice to extract the date out of the version number. I believe in adding the release date because that put a bit of pressure on package managers to move up the releases.

**Comment by johnyf** [comment]
I agree that date information is useful within a release. The development issue outlined [above](https://github.com/latex2html/latex2html/issues/2#issuecomment-275886890) can be regarded as an instance of the following problem: insert automatically information into a build. In this case, the information is the date. Usually, this issue arises about the version identifier itself.

In Python, people generally prefer to define the version at a single place. The approach I find the simplest is to place the date within the `setup.py` script of a Python package ([example](https://github.com/johnyf/dd/blob/01d917382cad24f0d48cde3f2ea2759e8a9a5544/setup.py#L22)). There is one caveat: `setup.py` is *outside* the package that it installs.

So, the version has to somehow be inserted in the package at the time of installation (for example, in the form of an auto-generated file [`_version.py`](https://github.com/johnyf/dd/blob/01d917382cad24f0d48cde3f2ea2759e8a9a5544/setup.py#L21)). Regarding installation, there are two use cases:

1. from within a repository (with `git` infrastructure present)
2. from a distribution archive that has been uploaded to PyPI (`git` absent)

The way others and I have approached this problem is to check automatically for a tag within `git` that matches the version number defined within `setup.py`. This number is dumped to a file called `_version.py`, and either installation or packaging for upload to PyPI continue from there in the same way. The file `_version.py` is ignored in `.gitignore`, and serves to store version information of a package that is distributed on PyPI, and when installed under `site-packages`.

One step further, obtaining versioning information from `git` comes handy during development, because non-releases are identified automatically as "development" versions, and the current commit hash (with "dirty" appended if applicable) is appended to the global version identifier, in order to obtain a local version identifier. This is especially useful during experimental development, profiling alternative implementations, and communicating with other developers (or revisiting an old development environment).

So, I would recommend using Python to obtain versioning information automatically at the time of release (e.g., with [`git_version`](https://github.com/johnyf/dd/blob/01d917382cad24f0d48cde3f2ea2759e8a9a5544/setup.py#L57)), both the version number (for deciding whether this is a release or development version, and to check the number against the one defined in a file tracked by `git`), as well as the date (which isn't the current date, but the date of the version tag, so this works on other dates too). Similarly to `_version.py`, a packaged distribution needs to include an auto-generated file with this information. I think that `git` itself is released in a similar way.

**Comment by danielgildea** [comment]
tagged v2017 and v2017.2

removed RCS version number from banner
