### ISSUE TITLE
installation error: can't locate L2hos.pm in @INC

### ISSUE THREAD

**Issue by johnyf** [latex2html/latex2html#3]
Unpacking [latex2html-2016.tar.gz](http://mirrors.ctan.org/support/latex2html/latex2html-2016.tar.gz) on a Linux Debian with `perl` installed and in the `$PATH`, I run `./configure` and got the error:

```
creating cache ./config.cache
checking for perl... /usr/bin/perl
checking whether #! works in shell scripts... yes
launching proprietary configuration...
Can't locate L2hos.pm in @INC (you may need to install the L2hos module) (@INC contains: lib /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.24.1 /usr/local/share/perl/5.24.1 /usr/lib/x86_64-linux-gnu/perl5/5.24 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.24 /usr/share/perl/5.24 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at ./config/config.pl line 436.
BEGIN failed--compilation aborted at ./config/config.pl line 436.
```

I had to add `export PERL5LIB="/path/to/latex2html-2016"` on the line https://github.com/latex2html/latex2html/blob/master/configure#L1160 in order to get `configure` to run successfully.

Running `make` failed for a similar reason. I had to run:

`export PERL5LIB="/path/to/latex2html-2016"; make`

Please let me know if I should have configured something differently. Otherwise, it seems that the installation instructions or the `configure` script and makefile need to be updated.

**Comment by danielgildea** [comment]
should be fixed now in git head
