### ISSUE TITLE
Merge Сергей Знаменский fork

### ISSUE THREAD

**Issue by pauloney** [latex2html/latex2html#33]
Сергей Знаменский has prepared some patches for Math-Net.ru in 2005

Try the test, related to the math formula vertical positioning at

    http://pier.botik.ru/~znamensk/test-scaled/

and use <Ctrl-+> and  <Ctrl--> in browser to see the result

The others changes are related to cyrillic encodings. I probably may be able to adapt them to mainstream version if problems appear.

You can just skip cyrillic text on the page

     http://wiki.botik.ru/LaTeX/LaTeX2html

With my beat regards, Sergej Znamenskij
Perealavl-Zalesskij, Russia

**Comment by danielgildea** [comment]
[75610e6475140593218bac919cdf03a8333056d3]
