### ISSUE TITLE
Perl execution doesn't work in fish shell

### ISSUE THREAD

**Issue by languitar** [latex2html/latex2html#38]
latex2html doesn't work in fish shell as the eval line of the unix wrapper cannot be parsed there:

```
Failed to execute process '/usr/bin/latex2html'. Reason:
exec: Exec format error
The file '/usr/bin/latex2html' is marked as an executable but could not be run by the operating system.
```

**Comment by danielgildea** [comment]
Works OK for me with fish.
The first line of the latex2html script is written by config.pl.
For me, it is "#! /usr/bin/perl".
What is it for you?

**Comment by languitar** [comment]
On archlinux this is:
```
# -*- perl -*- -w
eval '(exit $?0)' && eval 'exec /usr/bin/perl -S $0 ${1+"$@"}'
  & eval 'exec /usr/bin/perl -S $0 $argv:q'
  if 0; # suppress this stuff in perl

# The above lines start up perl on almost every shell,
# below we find usual perl code
```

**Comment by languitar** [comment]
Looks like the platform detection doesn't work properly inside the arch build environment.

**Comment by danielgildea** [comment]
This is caused by "--enable-wrapper" in the archlinux build script.
It looks like latex2html is behaving as expected, so I will close.

**Comment by languitar** [comment]
Ok, thanks. I have reported this back upstream.
