### ISSUE TITLE
require() calls fail with relative paths (code fix/hack included)

### ISSUE THREAD

**Issue by jaggzh** [latex2html/latex2html#42]
There are some errors with the require() lines.

**Issue 1:**
The line ~9244 (9277 in latex2html.pin) errors when I provide multiple .tex files, in reuse():
https://github.com/latex2html/latex2html/blob/master/latex2html.pin#L9277

Original line:
`require("$this_dir$dd${PREFIX}images.pl");`

I modified this to:
```
# If user-provided output dir is relative, prefix ./
#  so the require() won't fail
local $this_pfx = "./" if $this_dir !~ m|^/|;
require("$this_pfx$this_dir$dd${PREFIX}images.pl");

```

**Issue 2:**
https://github.com/latex2html/latex2html/blob/master/latex2html.pin#L2298
Similar issue with requiring internals.pl, except it seems the current working dir has been changed to the user-specified dir ($this_dir, above):

Original line:
`require ("${PREFIX}internals.pl") if (-f "${PREFIX}internals.pl");`
Modified:
```
local $internals_fn = "${PREFIX}internals.pl";
local $req_pfx = $internals_fn =~ m|^/| ? "" : "./";
require ("$req_pfx$internals_fn") if (-f "$internals_fn");
```

Nevertheless, the main graphics in intro.tex from the .bin (really a .tar) at: https://arxiv.org/format/1708.01692 don't come through.  See issue #41 for that.

**Comment by danielgildea** [comment]
I am not able to reproduce this problem.  Can you provide a test case?
