### ISSUE TITLE
latex2html 2018 does not handle html_version extensions

### ISSUE THREAD

**Issue by jarekczek** [latex2html/latex2html#44]
Hi Guys. I base so much on Latex2Html, that I decided to contribute a bit. At the moment by reporting some bugs. The first one is that the command:

C:\lang\latex\latex2html\bin\latex2html.bat -html_version 4.0,i18n simple

fails. It tries to load the file i18n, as if it doesn't recognize that it is an extension. Is it happening only on windows?

I just made an attribution on my page, which is generated with latex2html. Not very distinctive, but the link exists: [pbntools (attached software)](http://jarek.katowice.pl/ownsoft-en/pbntools-en#SECTION00031000000000000000). The program is open source, so all my latex2html workarounds are visible, that I apply to postprocess the html. If you like, I can file bug reports for all of them. The workarounds can be found in [build.xml](https://github.com/jarekczek/pbntools/blob/master/build.xml) file, searchable with "replaceAll".

**Comment by danielgildea** [comment]
Should be fixed in git - please test.

**Comment by bonsoftpl** [comment]
Seems like something went wrong. With 0e7f61166e19b24f I get the following error:

    Error: No files to process!

With previous commit be6c66dddae1d13b04 I was able to process some files.

**Comment by jarekczek** [comment]
Seems like something went wrong. With 0e7f611 I get the following error:

`Error: No files to process!`

With previous commit be6c66d I was able to process some files.

**Comment by danielgildea** [comment]
Can you try again?
I don't have windows available to test.

**Comment by jarekczek** [comment]
Works great. Thank you a lot!
