### ISSUE TITLE
Package dependancies?

### ISSUE THREAD

**Issue by niacdoial** [latex2html/latex2html#50]
Hello,
I guess this is more of a proposal than an issue.
Do you think you could make an installer for your program as well as the existing packages in the linux repositories (maybe using $TEXDIR to work)?

The thing is that I can't use the standard repository version of LaTeX2html, because I installed my TeXlive manually (https://www.tug.org/texlive/quickinstall.htm) and downloading the repository TeXlive completely messes up the existing installation.

If you  {can't/don't want to/think source access and installation instructions are enough}, I'll be fine myself.
Thanks!

**Comment by danielgildea** [comment]
I'm not sure exactly what you mean by an installer.

Does it work for you to say "./configure; make install" ?

**Comment by niacdoial** [comment]
I was thinking about a small (graphical) program that would ask for an installation directory (and maybe a few other settings) and run ./configure and make install (and add links in /usr/bin ?)

In hindsight, this probably was a dumb request, because to need this, someone has to know how to use LaTeX, have either MiKTeX or a non-repository version of TeXLive, and not be happy with the standard read README and INSTALL // edit a file // ./configure // make installation

Seriously the more I think about it the less sense it makes.
~~Maybe if it could work on every platform? but that would mean that it would be either 3 or 4 versions of the same pre-compiled program, or a python script, which adds the python dependency and uuuugh~~

Sorry for wasting your time.
Have a nice day ?

**Comment by danielgildea** [comment]
I see, thanks.  I think I will leave as is.
