### ISSUE TITLE
is creating an issue the only way of leaving a message 

### ISSUE THREAD

**Issue by captain-sensible** [latex2html/latex2html#54]
Not an issue but https://www.slackwiki.com/Writing_A_SlackBuild_Script references latex2html
trouble is there is nothing for noobs to download- so i created slackbuild using your latest release
for any die hards out there still using Slackware. I'm on 32 bit slackware 14.2 build runs, package created and it works converting .tex docs to html its here 

https://github.com/captain-sensible/latex2html.SlackBuild

**Comment by danielgildea** [comment]
Thanks for creating the package.  Since there are so many linux distributions,
I am only going to mention a few of the major ones on the main latex2html web page.
