### ISSUE TITLE
local .sty files not found 

### ISSUE THREAD

**Issue by captain-sensible** [latex2html/latex2html#56]
The slackbuild at https://slackbuilds.org/repository/14.2/academic/latex2html/?search=latex2html produces a package where the user can take advantage of .sty files located in : 
usr/share/texmf/tex/latex/

For custom .sty files it didn’t work for me. I respected a TLD structure : 

texmf
|-- bibtex
|   `-- bst
|       `-- aernobold.bst
|-- ls-R
`-- tex
    `-- latex
        |-- andystyle
        |   `-- andystyle.sty

 kpsewhich –var-value=TEXHOME confirmed texmf  , in my home directory as  place for tex and ran
$ texlsr texmf to update ls-R

using a text document eg 

\documentclass[11pt]{article}
\usepackage{xcolor}

successfully finds and makes use of  xcolor.sty in usr/share/texmf/tex/latex/ but does not find andystyle .sty  in the tree above.

In the configure flags I’m using in the slackbuild are :

./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --sysconfdir=/etc \
  --localstatedir=/var \
   --with-perl=/usr/bin/perl \
    --enable-pipes \
    --enable-shared=yes \
  --enable-paths  \
  --enable-eps \
  --enable-gif \
  --enable-png \
  --with-pdftocairo=/usr/bin/pdftocairo \
    --build=$ARCH-slackware-linux \
  --host=$ARCH-slackware-linux

the output when running

$ latex2html hello.tex is:

*********** WARNINGS ***********  
No implementation found for style `andystyle'
 

any ideas wht local .sty is not being found 

cheers

andy brookes

**Comment by danielgildea** [comment]
latex2html is looking for a .perl file that provides an html implementation for the style.
