### ISSUE TITLE
"make test" not working

### ISSUE THREAD

**Issue by garyscavone** [latex2html/latex2html#57]
After running configure, then make, I tried: make test ARGS='-debug'

But it seems to not find the included section files:

texexpand: %--- Found include at level 1: \include{basic}
texexpand: %--- checking for basic
texexpand: %--- looking for ./basic
texexpand: %--- looking for /Users/gary/Desktop/latex2html-master/basic
texexpand: %--- file not found
texexpand: include basic failed. Reinserting  command
...
The full output is in the attached file.
[l2htest.txt](https://github.com/latex2html/latex2html/files/4685074/l2htest.txt)

**Comment by garyscavone** [comment]
Can you provide some reason for why the test is not working before closing this issue?

**Comment by danielgildea** [comment]
I committed a fix - it should be working now.
