### ISSUE TITLE
Alignment, spacing in equation environment

### ISSUE THREAD

**Issue by garyscavone** [latex2html/latex2html#62]
I expect the spacing in the equation environment to be similar to the displaymath environment, with the addition of the equation number justified on the right margin. However, what I get is quite different.

First, there are no extra line breaks before and after the equation, so it gets lost in the preceding and following text.

Second, the equation is indented only a few spaces from the left side and the equation number comes almost immediately after.

Is there a way to fix this?

**Comment by danielgildea** [comment]
I am not getting this behavior.  Can you provide a minimal example?

**Comment by garyscavone** [comment]
The following example reproduces the behaviour for me and I’m attaching image of the resulting rendering on my system:

\documentclass{article}
\title{Test for eqnarray*}
\begin{document}

\begin{itemize}
\item First as an equation:
\begin{equation}
\tilde{y}(x,t) = C^{+} e^{j (\omega t - k x)} + C^{-} e^{j (\omega t + k x)},
\label{eq:yxt}
\end{equation}

\item Then using displaymath:
  \begin{displaymath}
    \tilde{y}(x,t) = C^{+} e^{j (\omega t - k x)} + C^{-} e^{j (\omega t + k x)},
\end{displaymath}
\end{itemize}

\end{document}
