### ISSUE TITLE
Error: Could not read directory "cweb2html": No such file or directory;____Warning: pstoimg not installed, because build failed; ____pstoimg.bat": No such file or directory

### ISSUE THREAD

**Issue by Sebastian-Nielsen** [latex2html/latex2html#65]
Info: Installed C:\usr\local\share\lib\latex2html\icons\blueball.gif
Info: Installed C:\usr\local\share\lib\latex2html\icons\ch_begin.gif
Info: Installed C:\usr\local\share\lib\latex2html\icons\ch_beg_r.gif
Info: Installed C:\usr\local\share\lib\latex2html\icons\ch_delet.gif
Info: Installed C:\usr\local\share\lib\latex2html\icons\ch_del_r.gif
Info: Installed C:\usr\local\share\lib\latex2html\icons\ch_end.gif
Info: Installed C:\usr\local\share\lib\latex2html\icons\ch_end_r.gif
Info: Installed C:\usr\local\share\lib\latex2html\icons\contents.gif
Info: Installed C:\usr\local\share\lib\latex2html\icons\crossref.gif
Info: Installed C:\usr\local\share\lib\latex2html\icons\footnote.gif
Info: Installed C:\usr\local\share\lib\latex2html\icons\greenball.gif
Info: Installed C:\usr\local\share\lib\latex2html\icons\icons.html
Info: Installed C:\usr\local\share\lib\latex2html\icons\image.gif
Info: Installed C:\usr\local\share\lib\latex2html\icons\index.gif
Info: Installed C:\usr\local\share\lib\latex2html\icons\next.gif
Info: Installed C:\usr\local\share\lib\latex2html\icons\next_g.gif
Info: Installed C:\usr\local\share\lib\latex2html\icons\nx_grp.gif
Info: Installed C:\usr\local\share\lib\latex2html\icons\nx_grp_g.gif
Info: Installed C:\usr\local\share\lib\latex2html\icons\orangeball.gif
Info: Installed C:\usr\local\share\lib\latex2html\icons\pinkball.gif
Info: Installed C:\usr\local\share\lib\latex2html\icons\prev.gif
Info: Installed C:\usr\local\share\lib\latex2html\icons\prev_g.gif
Info: Installed C:\usr\local\share\lib\latex2html\icons\purpleball.gif
Info: Installed C:\usr\local\share\lib\latex2html\icons\pv_grp.gif
Info: Installed C:\usr\local\share\lib\latex2html\icons\pv_grp_g.gif
Info: Installed C:\usr\local\share\lib\latex2html\icons\redball.gif
Info: Installed C:\usr\local\share\lib\latex2html\icons\up.gif
Info: Installed C:\usr\local\share\lib\latex2html\icons\up_g.gif
Info: Installed C:\usr\local\share\lib\latex2html\icons\whiteball.gif
Info: Installed C:\usr\local\share\lib\latex2html\icons\yellowball.gif
Info: Installed C:\usr\local\share\lib\latex2html\IndicTeX-HTML\bengali.perl
Info: Installed C:\usr\local\share\lib\latex2html\IndicTeX-HTML\bengali.sty
Info: Installed C:\usr\local\share\lib\latex2html\IndicTeX-HTML\devnagri.perl
Info: Installed C:\usr\local\share\lib\latex2html\IndicTeX-HTML\devnagri.sty
Info: Installed C:\usr\local\share\lib\latex2html\IndicTeX-HTML\gujarati.perl
Info: Installed C:\usr\local\share\lib\latex2html\IndicTeX-HTML\gujarati.sty
Info: Installed C:\usr\local\share\lib\latex2html\IndicTeX-HTML\gurmukhi.perl
Info: Installed C:\usr\local\share\lib\latex2html\IndicTeX-HTML\gurmukhi.sty
Info: Installed C:\usr\local\share\lib\latex2html\IndicTeX-HTML\hindi.perl
Info: Installed C:\usr\local\share\lib\latex2html\IndicTeX-HTML\hindi.sty
Info: Installed C:\usr\local\share\lib\latex2html\IndicTeX-HTML\indica.perl
Info: Installed C:\usr\local\share\lib\latex2html\IndicTeX-HTML\indica.sty
Info: Installed C:\usr\local\share\lib\latex2html\IndicTeX-HTML\itrans.perl
Info: Installed C:\usr\local\share\lib\latex2html\IndicTeX-HTML\itrans.sty
Info: Installed C:\usr\local\share\lib\latex2html\IndicTeX-HTML\kannada.perl
Info: Installed C:\usr\local\share\lib\latex2html\IndicTeX-HTML\kannada.sty
Info: Installed C:\usr\local\share\lib\latex2html\IndicTeX-HTML\malyalam.perl
Info: Installed C:\usr\local\share\lib\latex2html\IndicTeX-HTML\malyalam.sty
Info: Installed C:\usr\local\share\lib\latex2html\IndicTeX-HTML\oriya.perl
Info: Installed C:\usr\local\share\lib\latex2html\IndicTeX-HTML\oriya.sty
Info: Installed C:\usr\local\share\lib\latex2html\IndicTeX-HTML\README.IndicTeX-HTML
Info: Installed C:\usr\local\share\lib\latex2html\IndicTeX-HTML\sanskrit.perl
Info: Installed C:\usr\local\share\lib\latex2html\IndicTeX-HTML\sanskrit.sty
Info: Installed C:\usr\local\share\lib\latex2html\IndicTeX-HTML\sinhlese.perl
Info: Installed C:\usr\local\share\lib\latex2html\IndicTeX-HTML\sinhlese.sty
Info: Installed C:\usr\local\share\lib\latex2html\IndicTeX-HTML\tamil.perl
Info: Installed C:\usr\local\share\lib\latex2html\IndicTeX-HTML\tamil.sty
Info: Installed C:\usr\local\share\lib\latex2html\IndicTeX-HTML\telugu.perl
Info: Installed C:\usr\local\share\lib\latex2html\IndicTeX-HTML\telugu.sty
Info: Installed C:\usr\local\share\lib\latex2html\IndicTeX-HTML\tibetan.perl
Info: Installed C:\usr\local\share\lib\latex2html\IndicTeX-HTML\tibetan.sty
Info: Installed C:\usr\local\share\lib\latex2html\L2hos\Dos.pm
Info: Installed C:\usr\local\share\lib\latex2html\L2hos\Mac.pm
Info: Installed C:\usr\local\share\lib\latex2html\L2hos\OS2.pm
Info: Installed C:\usr\local\share\lib\latex2html\L2hos\Unix.pm
Info: Installed C:\usr\local\share\lib\latex2html\L2hos\Win32.pm
Info: Installed C:\usr\local\share\lib\latex2html\L2hos.pm
Info: Installed C:\usr\local\share\lib\latex2html\XyMTeX-HTML\aliphat.perl
Info: Installed C:\usr\local\share\lib\latex2html\XyMTeX-HTML\carom.perl
Info: Installed C:\usr\local\share\lib\latex2html\XyMTeX-HTML\ccycle.perl
Info: Installed C:\usr\local\share\lib\latex2html\XyMTeX-HTML\chemstr.perl
Info: Installed C:\usr\local\share\lib\latex2html\XyMTeX-HTML\chemsym.perl
Info: Installed C:\usr\local\share\lib\latex2html\XyMTeX-HTML\hcycle.perl
Info: Installed C:\usr\local\share\lib\latex2html\XyMTeX-HTML\hetarom.perl
Info: Installed C:\usr\local\share\lib\latex2html\XyMTeX-HTML\hetaromh.perl
Info: Installed C:\usr\local\share\lib\latex2html\XyMTeX-HTML\locant.perl
Info: Installed C:\usr\local\share\lib\latex2html\XyMTeX-HTML\lowcycle.perl
Info: Installed C:\usr\local\share\lib\latex2html\XyMTeX-HTML\xymman.perl
Info: Installed C:\usr\local\lib\latex2html\cfgcache.pm
**Error: Could not read directory "cweb2html": No such file or directory**
Info: Installed C:\usr\local\share\lib\latex2html\docs\.latex2html-init
Info: Installed C:\usr\local\share\lib\latex2html\docs\appendix.tex
Info: Installed C:\usr\local\share\lib\latex2html\docs\credits.tex
Info: Installed C:\usr\local\share\lib\latex2html\docs\features.tex
Info: Installed C:\usr\local\share\lib\latex2html\docs\hypextra.tex
Info: Installed C:\usr\local\share\lib\latex2html\docs\l2hfiles.dat
Info: Installed C:\usr\local\share\lib\latex2html\docs\l2hglo.ist
Info: Installed C:\usr\local\share\lib\latex2html\docs\l2hidx.ist
Info: Installed C:\usr\local\share\lib\latex2html\docs\l2hman.sty
Info: Installed C:\usr\local\share\lib\latex2html\docs\licence.tex
Info: Installed C:\usr\local\share\lib\latex2html\docs\Makefile
Info: Installed C:\usr\local\share\lib\latex2html\docs\manhtml.tex
Info: Installed C:\usr\local\share\lib\latex2html\docs\manual.index
Info: Installed C:\usr\local\share\lib\latex2html\docs\manual.tex
Info: Installed C:\usr\local\share\lib\latex2html\docs\overview.tex
Info: Installed C:\usr\local\share\lib\latex2html\docs\problems.tex
Info: Installed C:\usr\local\share\lib\latex2html\docs\support.tex
Info: Installed C:\usr\local\share\lib\latex2html\docs\userman.tex
Info: Installed C:\usr\local\share\lib\latex2html\docs\hthtml\hthtml.tex
Info: Installed C:\usr\local\share\lib\latex2html\docs\hthtml\Makefile
Info: Installed C:\usr\local\share\lib\latex2html\docs\hthtml\readme.hthtml
Info: Installed C:\usr\local\share\lib\latex2html\docs\psfiles\dn.gif
Info: Installed C:\usr\local\share\lib\latex2html\docs\psfiles\eform.ps
Info: Installed C:\usr\local\share\lib\latex2html\docs\psfiles\eform2.ps
Info: Installed C:\usr\local\share\lib\latex2html\docs\psfiles\eqarrA1.ps
Info: Installed C:\usr\local\share\lib\latex2html\docs\psfiles\eqarrA15.ps
Info: Installed C:\usr\local\share\lib\latex2html\docs\psfiles\eqarrA2.ps
Info: Installed C:\usr\local\share\lib\latex2html\docs\psfiles\eqarrB1.ps
Info: Installed C:\usr\local\share\lib\latex2html\docs\psfiles\eqarrB15.ps
Info: Installed C:\usr\local\share\lib\latex2html\docs\psfiles\eqarrB2.ps
Info: Installed C:\usr\local\share\lib\latex2html\docs\psfiles\eqn1.ps
Info: Installed C:\usr\local\share\lib\latex2html\docs\psfiles\eqn15.ps
Info: Installed C:\usr\local\share\lib\latex2html\docs\psfiles\eqn2.ps
Info: Installed C:\usr\local\share\lib\latex2html\docs\psfiles\figure.ps
Info: Installed C:\usr\local\share\lib\latex2html\docs\psfiles\HTMLtab.ps
Info: Installed C:\usr\local\share\lib\latex2html\docs\psfiles\table.ps
Info: Installed C:\usr\local\share\lib\latex2html\docs\psfiles\up.gif
Info: Installed C:\usr\local\share\lib\latex2html\dot.latex2html-init
Info: Installed C:\usr\local\share\lib\latex2html\example\Makefile
Info: Installed C:\usr\local\share\lib\latex2html\example\report.tex
Info: Installed C:\usr\local\share\lib\latex2html\example\sec1.tex
Info: Installed C:\usr\local\share\lib\latex2html\example\sec2.tex
Info: Installed C:\usr\local\share\lib\latex2html\foilhtml\foilhtml.dtx
Info: Installed C:\usr\local\share\lib\latex2html\foilhtml\foilhtml.ins
Info: Installed C:\usr\local\share\lib\latex2html\foilhtml\readme.v12
Info: Installed C:\usr\local\lib\latex2html\l2hconf.pm
Info: Installed C:\usr\local\bin\latex2html.bat
Info: Installed C:\usr\local\share\lib\latex2html\makemap
Info: Installed C:\usr\local\share\lib\latex2html\makeseg\makeseg
Info: Installed C:\usr\local\share\lib\latex2html\makeseg\makeseg.tex
**Warning: pstoimg not installed, because build failed.**
Info: Installed C:\usr\local\share\lib\latex2html\styles\abnt.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\afrikaan.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\alltt.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\american.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\amsart.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\amsbook.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\amsfonts.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\amsmath.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\amssymb.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\amstex.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\article.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\austrian.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\babel.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\babelbst.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\bahasa.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\book.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\brazil.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\breton.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\catalan.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\changebar.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\CJK.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\color.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\colordvi.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\crayola.txt
Info: Installed C:\usr\local\share\lib\latex2html\styles\croatian.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\czech.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\danish.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\dutch.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\english.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\enumerate.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\epsbox.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\epsfig.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\esperant.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\estonian.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\eurosym.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\finnish.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\floatfig.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\floatflt.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\fontenc.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\frames.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\francais.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\french.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\galician.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\german.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\germanb.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\getimagesize.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\graphics-support.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\graphics.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\graphicx.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\harvard.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\heqn.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\hthtml.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\html.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\htmllist.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\hyperref.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\inputenc.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\irish.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\italian.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\justify.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\latexsym.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\letter.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\longtable.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\lsorbian.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\luacode.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\luainputenc.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\lyx.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\magyar.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\makeidx.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\more_amsmath.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\multicol.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\multirow.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\natbib.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\norsk.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\nynorsk.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\polish.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\polski.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\polyglossia.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\portuges.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\psfrag.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\report.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\rgb.txt
Info: Installed C:\usr\local\share\lib\latex2html\styles\romanian.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\russian.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\scottish.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\seminar.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\SIunits.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\slides.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\slovak.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\slovene.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\spanish.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\supertabular.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\t2a.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\TEMPLATE.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\texdefs.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\texnames.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\textcomp.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\turkish.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\usorbian.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\verbatim.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\verbatimfiles.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\webtex.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\welsh.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\wrapfig.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\xcolor.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\xspace.perl
Info: Installed C:\usr\local\share\lib\latex2html\styles\xy.perl
Info: Installed C:\usr\local\bin\texexpand.bat
Info: Installed C:\usr\local\share\lib\latex2html\texinputs\frames.sty
Info: Installed C:\usr\local\share\lib\latex2html\texinputs\heqn.sty
Info: Installed C:\usr\local\share\lib\latex2html\texinputs\hthtml.sty
Info: Installed C:\usr\local\share\lib\latex2html\texinputs\html.sty
Info: Installed C:\usr\local\share\lib\latex2html\texinputs\htmllist.sty
Info: Installed C:\usr\local\share\lib\latex2html\texinputs\justify.sty
Info: Installed C:\usr\local\share\lib\latex2html\texinputs\ldump.sty
Info: Installed C:\usr\local\share\lib\latex2html\texinputs\techexplHTML.tex
Info: Installed C:\usr\local\share\lib\latex2html\texinputs\verbatimfiles.sty
Info: Installed C:\usr\local\share\lib\latex2html\versions\cp1251.pl
Info: Installed C:\usr\local\share\lib\latex2html\versions\cp1252.pl
Info: Installed C:\usr\local\share\lib\latex2html\versions\decmulti.pl
Info: Installed C:\usr\local\share\lib\latex2html\versions\frame.pl
Info: Installed C:\usr\local\share\lib\latex2html\versions\hebrew.pl
Info: Installed C:\usr\local\share\lib\latex2html\versions\html3_0.pl
Info: Installed C:\usr\local\share\lib\latex2html\versions\html3_1.pl
Info: Installed C:\usr\local\share\lib\latex2html\versions\html3_2.pl
Info: Installed C:\usr\local\share\lib\latex2html\versions\html4_0.pl
Info: Installed C:\usr\local\share\lib\latex2html\versions\html4_01.pl
Info: Installed C:\usr\local\share\lib\latex2html\versions\html4_1.pl
Info: Installed C:\usr\local\share\lib\latex2html\versions\html5_0.pl
Info: Installed C:\usr\local\share\lib\latex2html\versions\i18n.pl
Info: Installed C:\usr\local\share\lib\latex2html\versions\koi8.pl
Info: Installed C:\usr\local\share\lib\latex2html\versions\lang.pl
Info: Installed C:\usr\local\share\lib\latex2html\versions\latin1.pl
Info: Installed C:\usr\local\share\lib\latex2html\versions\latin2.pl
Info: Installed C:\usr\local\share\lib\latex2html\versions\latin3.pl
Info: Installed C:\usr\local\share\lib\latex2html\versions\latin4.pl
Info: Installed C:\usr\local\share\lib\latex2html\versions\latin5.pl
Info: Installed C:\usr\local\share\lib\latex2html\versions\latin6.pl
Info: Installed C:\usr\local\share\lib\latex2html\versions\latin7.pl
Info: Installed C:\usr\local\share\lib\latex2html\versions\latin8.pl
Info: Installed C:\usr\local\share\lib\latex2html\versions\latin9.pl
Info: Installed C:\usr\local\share\lib\latex2html\versions\macroman.pl
Info: Installed C:\usr\local\share\lib\latex2html\versions\math.pl
Info: Installed C:\usr\local\share\lib\latex2html\versions\techexpl.pl
Info: Installed C:\usr\local\share\lib\latex2html\versions\unicode.pl
Info: Installed C:\usr\local\share\lib\latex2html\versions\utf8.pl
Info: Installed C:\usr\local\share\lib\latex2html\versions\utf8ru.pl
Done. Have a lot of fun with LaTeX2HTML!

C:\Users\sebas\Downloads\latex2html\latex2html>test.bat
... checking latex2html
C:\Users\sebas\Downloads\latex2html\latex2html\latex2html.bat syntax OK
... checking texexpand
C:\Users\sebas\Downloads\latex2html\latex2html\texexpand.bat syntax OK
... checking pstoimg
Can't open perl script "C:\Users\sebas\Downloads\latex2html\latex2html\pstoimg.bat": No such file or directory

How do I fix the error and warning in the above?

**Comment by danielgildea** [comment]
This doesn't include output from the build, so I'm not sure why the build failed.  I also don't have a windows machine to test on.  You might get more information from windows users on the mailing list.
