### ISSUE TITLE
Translating images to PDF using pdflatex : epstopdf Cannot open file.eps

### ISSUE THREAD

**Issue by cessenat** [latex2html/latex2html#68]
When using pdftex, epstopdf.pl complains it cannot find the eps file ; one must alter texlive's epstopdf.pl and make it open "../$InputFilename" so that it works (line 695 of epstopdf.pl).
I tried with master and latest release of latex2html. I tried on CentOS7.8 and Ubuntu 18.04.
I used texlive 2020 and 2021 on CentOS 7.8 and the one of the distrib on Ubuntu. 

With -nouse_pdftex there is no such problem.
I include the latex file, the eps file can be any.
Error is:

> $ latex2html -local_icons -show_section_numbers mydoc

```
Translating images to PDF using pdflatex ...
This is pdfTeX, Version 3.14159265-2.6-1.40.21 (TeX Live 2020 - Spack) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./images.tex
LaTeX2e <2020-02-02> patch level 5
L3 programming layer <2020-03-06>
* Restricted mode activated
* kpsewhich command: kpsewhich
* Input filename: decoup32l.eps
* Output filename: decoup32l-eps-converted-to.pdf
* BoundingBox comment: %%BoundingBox:
* Ghostscript command: gs
* Compression: on
* Embedding: on
* Grayscale: off
* PDFSettings: prepress
* Resolution: [use gs default]
* Rotation: None
epstopdf ($Id: epstopdf.pl 48681 2018-09-16 23:03:58Z karl $) 2.28
!!! Error: Cannot open decoup32l.eps: No such file or directory
system returned with code 512

```
Latex file is
```
\documentclass[12pt]{article}
\usepackage[dvips]{graphicx}
\begin{document}
\author{Olivier Cessenat}
\title{Example for latex2html includes eps.}
\date{\today.}
\listoffigures
\section{Introduction}
Refer to picture \ref{decoup32l}
\begin{figure}[th!]
\caption{A split example.}\label{decoup32l}
\begin{center}
\includegraphics[width=0.98\textwidth]{decoup32l.eps}
\end{center}
\end{figure}
\end{document}

```
Thanks for your help,
Olivier Cessenat

**Comment by danielgildea** [comment]
I don't think this is technically a bug.  Generally speaking, if your
document does not compile with pdflatex, you have to use -nouse_pdftex.
See also #53.

**Comment by cessenat** [comment]
Thanks @danielgildea for your quick reply and pointer ; still, I have not understood a few things:
-a) when I run pdflatex it does not create the decoup32l.pdf file, 
-b) when I convert the decoup32l.eps to decoup32l.pdf and run pdflatex it raises an error (while latex2html works fine !),
-c) is there a way to modify the call to epstopdf.pl such as cat ../decoup32l.eps | epstopdf.pl --filter > decoup32l-eps-converted-to.pdf ? I was unable to find where the conversion is called from in latex2html.
Thanks very much if you can again help me for that !
Cheers,
Olivier Cessenat

**Comment by danielgildea** [comment]
> -a) when I run pdflatex it does not create the decoup32l.pdf file,

This works for me if I replace `\usepackage[dvips]{graphicx}`
with `\usepackage{graphicx}`.

> -b) when I convert the decoup32l.eps to decoup32l.pdf and run pdflatex it raises an error (while latex2html works fine !),

This should work if you get rid of `[dvips]`.

> -c) is there a way to modify the call to epstopdf.pl such as cat ../decoup32l.eps | epstopdf.pl --filter > decoup32l-eps-converted-to.pdf ? I was unable to find where the conversion is called from in latex2html.

epsetopdf.pl is called by latex, not by latex2html, so I don't know how to modify the call.

**Comment by cessenat** [comment]
Thank you very much @danielgildea everything works after getting rid of the dvips option as you indicated.
It is a great software latex2html, thank you for taking care of it !
