### ISSUE TITLE
Equation numbers not right-justified with equation environment.

### ISSUE THREAD

**Issue by rileyle** [latex2html/latex2html#69]
Some LaTeX source and a screenshot of the output below (v2019.2). I see right-justified numbering with the `eqnarray` environment.

`The potential difference $V$ between the terminals of an \textbf{Ohmic
device} is directly proportional to the current $I$ flowing through it,

\begin{equation}
  V=IR
\label{eq:Ohm}
\end{equation}

The constant of proportionality $R$ is called the \textbf{resistance}
of the device. Equation~\ref{eq:Ohm} is known as \textbf{Ohm's
Law}. Ohmic devices called \textbf{resistors} are ubiquitous in
electronic circuits. When current flows through a resistor, power is
dissipated in the form of heat and light. The power dissipated in a
resistor given by

\begin{equation}
  P_\mathrm{diss} = I^2 R = \frac{V^2}{R}
\end{equation}`

![eqno_output](https://user-images.githubusercontent.com/20118141/122059108-4af34480-cdba-11eb-9567-8ed84310560e.png)

**Comment by danielgildea** [comment]
works ok for me with current sources - can you try that?

**Comment by rileyle** [comment]
Works fine with v2021.
