### ISSUE TITLE
latex2html compability code in hyperref

### ISSUE THREAD

**Issue by u-fischer** [latex2html/latex2html#72]
The hyperref dtx contains a section "\section{Compatibility with the \emph{\LaTeX{}2html} package}"

I would like to remove the code there in the next hyperref version. It hasn't been changed for ages and after looking a bit at html.sty I suspect that parts or all of the hyperref patches are outdated. But I'm not a latex2html user, I can't test if these definitions are still needed.

So please could you check the following definitions? If you think that one of it is still necessary, please give me an example or test file for it.

~~~~
% \section{Compatibility with the \emph{\LaTeX{}2html} package}\label{latex2html}
%
% Map our macro names on to Nikos', so that documents prepared
% for that system will work without change.
%
% Note, however, that the whole complicated structure for
% segmenting documents is not supported; it is assumed that the user
% will load |html.sty| first, and then |hyperref.sty|, so that the
% definitions in |html.sty| take effect, and are then overridden
% in a few circumstances by this package.
%    \begin{macrocode}
\let\htmladdimg\hyperimage
%    \end{macrocode}
%
%    \begin{macrocode}
\def\htmladdnormallink#1#2{\href{#2}{#1}}
\def\htmladdnormallinkfoot#1#2{\href{#2}{#1}\footnote{#2}}
\def\htmlref#1#2{% anchor text, label
  \label@hyperref[{#2}]{#1}%
}
%    \end{macrocode}
% This is really too much. The \LaTeX2html package defines its own
% |\hyperref| command, with a different syntax. Was this always here?
% Its weird, anyway. We interpret it in the `printed' way, since
% we are about fidelity to the page.
%    \begin{macrocode}
\def\@@latextohtmlX{%
  \let\hhyperref\hyperref
  \def\hyperref##1##2##3##4{% anchor text for HTML
                     % text to print before label in print
                     % label
                     % post-label text in print
    ##2\ref{##4}##3%
  }%
}
%    \end{macrocode}
~~~~

**Comment by danielgildea** [comment]
This code is used when documents include html.sty and hyperref.sty with latex+dvips, but not with pdflatex.  Here is test case.

[hyper.tex.zip](https://github.com/latex2html/latex2html/files/7077463/hyper.tex.zip)

**Comment by u-fischer** [comment]
Thanks for the test file. 

It compiles with pdflatex but fails with latex+dvips. But it doesn't make a difference if the hyperref compability code is there or not. 

So I will remove this section from hyperref.

**Comment by danielgildea** [comment]
It compiles with latex+dvips if the hyperref package is given the latex2html option.
[hyper.tex.zip](https://github.com/latex2html/latex2html/files/7078551/hyper.tex.zip)

**Comment by u-fischer** [comment]
Yes. And there the redefinition of `\hyperref` is needed. But I don't see a reason why this should be done hyperref and so need a package option. 

So please redefine `\hyperref` in `\AtBeginDocument` yourself to whatever you need. 

I will leave the latex2html package option but make it a void option (or issue a warning) so that it does nothing.
