### ISSUE TITLE
Fails to process C++ draft

### ISSUE THREAD

**Issue by hinell** [latex2html/latex2html#75]
I'm trying to convert the [C++ draft] with older version but It fails with very weird stdout output.  Will try to use a newer and see if it works.

[C++ draft]: https://github.com/cplusplus/draft

## Steps to rerproduce
```bash
git clone --depth 1 --no-tags git@github.com:cplusplus/draft.git /tmp/
cd /tmp/draft/source
latex2html std.tex
```

## Versions
* `latex2html` -  Version 2021 ([Released January 1, 2021](https://packages.debian.org/sid/latex2html))

**Comment by danielgildea** [comment]
This document uses quite a few latex packages that haven't been implemented in latex2html.
