### ISSUE TITLE
Conversion skipping some formulas 

### ISSUE THREAD

**Issue by Davegb** [latex2html/latex2html#78]
I'm trying to convert my document (source attached). When it gets to section 2.6 (EBGW), there's a part when it should show 3 equations, each one with two cases like this:

![image](https://user-images.githubusercontent.com/12886612/179666385-5c532251-c314-4d3f-9b58-120aaf4a9725.png)

However, it doesn't appear. And also, after that, some math symbols (C2, G1) are also skipped. From then on, the document gets a bit crazy. Is there any way I can fix it?

Here's the source:

[supp.zip](https://github.com/latex2html/latex2html/files/9137514/supp.zip)
 
Thanks!

**Comment by danielgildea** [comment]
This example works for me, so I'm not sure what the problem is.  Are you using the latest version of latex2html?  Are you using any command line options or config files?

**Comment by Davegb** [comment]
I was on a Chromebook using Crostini, so I was using the version from the Debian repo. Now I'm trying on Fedora, also the version on the Fedora repo, and it works. Thanks! One more question: I'm getting the following error on Fedora:

```
*********** WARNINGS ***********  
No implementation found for style `caption'

\bibitem label format not supported, using \bibcite information!

Unknown commands: protected_at_file_at_percent
```

Is it relevant?

**Comment by Davegb** [comment]
Looks like the problem arises when I run the command `latex2html supp.tex` for a second time without deleting the `supp` directory. Also, some formulas appear bigger than they should, like the one in the original post, but I can modify that. 

Two more questions: 
* When I generated the HTML, I got the following warning:
*```
********** WARNINGS ***********  
No implementation found for style `caption'

\bibitem label format not supported, using \bibcite information!

Unknown commands: protected_at_file_at_percent
```

Is it relevant? 

* When I generate the HTML as a single page using `-split 0`, is there a way to make the index appear at the top with links to each section? Or I'd have to do that manually?

**Comment by danielgildea** [comment]
> Looks like the problem arises when I run the command `latex2html supp.tex` for a second time without deleting the `supp` directory.

Latex2html doesn't regenerate the images, so if you run with the old version, and then run with the new version, you will still have the bad images.  Running twice with the latest latex2html works for me.

>  Also, some formulas appear bigger than they should, like the one in the original post, but I can fix that myself.
> 
> Two more questions:
> 
>     * When I generated the HTML, I got the following warning:
> 
> 
> ```
> ********** WARNINGS ***********  
> No implementation found for style `caption'
> 
> \bibitem label format not supported, using \bibcite information!
> 
> Unknown commands: protected_at_file_at_percent
> ```

Those indicate latex commands not supported by latex2html, but I don't think they are connected to your problem with the equations.


> 
>     * When I generate the HTML as a single page using `-split 0`, is there a way to make the index appear at the top with links to each section? Or I'd have to do that manually?

You can `\usepackage{html}` and then say  `\tableofchildlinks` at the beginning of the document.
